// export const Fetch_Products = 'Fetch_Products'
// export const Fetch_Category = 'Fetch_Category'
export const Fetch_Wishlist = 'Fetch_Wishlist'
export const Add_To_Wishlist = 'Add_To_Wishlist'
export const Remove_From_Wishlist = 'Remove_From_Wishlist'
export const Add_To_Cart = 'Add_To_Cart'
export const Remove_From_Cart = 'Remove_From_Cart'